[[configuration]]
== Configuration

The plugin provide a default configuration, but you may add your own settings in your *Config.groovy* for Grails 2.x and *application.groovy* or *application.yml* for Grails > 3.x.

=== Overriding Spring Boot elasticsearch version

Spring Boot 3.5.x supports Elasticsearch 8.18.x OOTB and will install dependencies for this version, if not explicitly overriden. To do so add the following to your `build.gradle`:

[source, groovy]
----
def elasticsearchVersion = '7.17.29'
ext['elasticsearch.version'] = elasticsearchVersion
----

=== Default configuration script

Below is the default configuration loaded by the plugin (any of your settings in the Config.groovy script overwrite those).

[source, groovy]
.Config.groovy
----
elasticSearch {
  /**
   * Date formats used by the unmarshaller of the JSON responses
   */
  date.formats = ["yyyy-MM-dd'T'HH:mm:ss.S'Z'"]

  /**
   * Hosts for remote ElasticSearch instances.
   * Will only be used with the "transport" client mode.
   * If the client mode is set to "transport" and no hosts are defined, ["localhost", 9200] will be used by default. We are using the REST port of ElasticSearch.
   */
  client.hosts = [
          [host: 'localhost', port: 9200]
  ]

  /**
   * Whether to enable SSL for the ElasticSearch client.
   */
  client.ssl.enabled = false

  /**
   * The strategy for validating SSL connections.
   *
   * Possible values:
   *   - "all": trust all certificates; least secure, only use for development
   *   - "self-signed": trust self-signed certificates; use in trusted environments like a properly secured docker-stack
   *   - "trust-store": use a given trust store; requires trust-store file and credentials
   */
  client.ssl.trust = 'all'

  /**
   * If <code>client.ssl.trust</code> is set to "trust-store", you need to provide the path to the trust store file here.
   */
  client.ssl.truststore.file = ''

  /**
   * If <code>client.ssl.trust</code> is set to "trust-store", you need to provide the credentials for the trust store file here.
   */
  client.ssl.truststore.password = ''

  /**
   * Default mapping property exclusions
   *
   * No properties matching the given names will be mapped by default
   * i.e., when using "searchable = true"
   *
   * This does not apply for classes using mapping by closure
   */
  defaultExcludedProperties = ["password"]

  /**
   * Determines if the plugin should reflect any database save/update/delete automatically
   * on the ES instance. Default to false.
   */
  disableAutoIndex = false

  /**
   * Should the database be indexed at startup.
   *
   * The value may be a boolean true|false.
   * Indexing is always asynchronous (compared to Searchable plugin) and executed after BootStrap.groovy.
   */
  bulkIndexOnStartup = true

  /**
   *  Max number of requests to process at once. Reduce this value if you have memory issue when indexing a big amount of data
   *  at once. If this setting is not specified, 500 will be use by default.
   */
  maxBulkRequest = 500


  /**
   * The name of the ElasticSearch mapping configuration property that annotates domain classes. The default is 'searchable'.
   */
  searchableProperty.name = 'searchable'
}

environments {
  development {
    /**
     * Possible values: "transport"
     */
    elasticSearch.client.mode = 'transport'
  }
  test {
    elasticSearch.client.mode = 'transport'
  }
  production {
    elasticSearch.client.mode = 'transport'
  }
}
----

==== Grails 7.x Sample YAML configuration

[source, yaml]
.application.yml
----
elasticSearch:
    date:
        formats: ["yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"]
    client:
        hosts:
            - {host: localhost, port: 9200}
        # For xpack.security enabled Elasticsearch instances
        ssl:
            enabled: true
            trust: 'self-signed'
        username: 'elastic'
        password: 'changeme'
    defaultExcludedProperties: ['password']
    disableAutoIndex: false
    index:
        compound_format: true
    unmarshallComponents: true
    searchableProperty:
        name: searchable
    includeTransients: false
environments:
    development:
        elasticSearch:
            client:
                mode: transport
                transport.sniff: true
            bulkIndexOnStartup: true
    test:
        elasticSearch:
            client:
                mode: transport
                transport.sniff: true
            datastoreImpl: hibernateDatastore
            index:
                store.type: memory
                settings:
                    analysis:
                        filter:
                            replace_synonyms:
                                type: synonym
                                synonyms: ['abc => xyz']
                        analyzer:
                            test_analyzer:
                                tokenizer: standard
                                filter: ['lowercase']
                            repl_analyzer:
                                tokenizer: standard
                                filter: ['lowercase', 'replace_synonyms']

    production:
        elasticSearch:
            client:
                mode: transport
----
[INFO]
====
For *Grails > 4* and *elasticsearch plugin > 3.0.0* you need to configure the REST port 9200 instead of the obsolete port 9300.
====

=== Client mode

Since plugin version 3.x we only support the transport ("REST") mode, detailed on the https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/7.17/index.html[official ElasticSearch documentation].
The mode is defined with the following config key:

[source, groovy]
.applicaiton.groovy or Config.groovy
----
elasticSearch.client.mode = '<mode>'
----

[source, yml]
.application.yml
----
elasticSearch:
    client:
        mode: <mode>
----

"transport" mode needs you to provide the host address and port. You can define one or multiple hosts with the following config key:

[source,groovy]
.application.groovy or Config.groovy
----
elasticSearch.client.hosts = [
       [host: '192.168.0.3', port: 9200],
       [host: '228.168.0.4', port: 9200]
]
----

[source, yaml]
.application.yml
----
elasticSearch:
  client:
    hosts:
      - {host: 192.168.0.3, port: 9200}
      - {host: 228.168.0.4, port: 9200}
----

If no host is defined, `localhost:9200` will be used by the transport client.

==== Disable Mapper Attachment plugin

The Mapper Attachment plugin is Deprecated since version 5.0.0 and will be replaced by https://www.elastic.co/guide/en/elasticsearch/plugins/5.0/ingest-attachment.html[ingest-attachment] plugin.

So, if you are using ES plugin with mode: `local` and do not want to use Mapper Attachment plugin then you can disable the plugin by using the following configuration:

[source, yaml]
.application.yml
----
elasticSearch:
    plugin:
        mapperAttachment:
            enabled: false
----

[NOTE]
====
Please note that by default the plugin is enabled.
====


=== Security and SSL

If your Elasticsearch cluster is secured, using XPack security for example, you can configure the plugin to use authentication and SSL.

==== Authentication

To use authentication in the client, you have to set username and password:

[source, yaml]
.application.yml
----
elasticSearch:
  client:
    username: elastic
    password: changeme
----

==== SSL Configuration

To enable SSL and configure the trust strategy, use the following configuration:

[source, yaml]
.application.yml
----
elasticSearch:
  client:
    ssl:
      enabled: true
      trust: self-signed # 'all', 'self-signed', or 'trust-store'
----

.SSL Trust Strategies
[width="100%",cols="2",options="header"]
|===
|Value |Description

| `all`
| Trust all certificates. This is the least secure and should only be used for development.

| `self-signed`
| Trust self-signed certificates. This is useful for environments with limited access like a properly secured Docker stack.

| `trust-store`
| Use a specific trust store. This requires additional configuration for the trust store file and password. Use this for Elasticsearch clusters used by many applications and accessible by more than just your Grails app.
|===

===== Using a Trust Store

If you use the `trust-store` trust-strategy, you must provide the path to the trust store file and its password:

[source, yaml]
.application.yml
----
elasticSearch:
  client:
    ssl:
      enabled: true
      trust: trust-store
      truststore:
        file: /path/to/elasticsearch-truststore.jks
        password: super_secure
----

To create a trust store from an Elasticsearch CA certificate, you can use the `keytool` command:

[source, bash]
----
keytool -importcert -alias elasticsearch-ca -file ca.crt -keystore elasticsearch-truststore.jks -storetype JKS -storepass super_secure
----


=== Mapping Migration properties

Define the application's behaviour when a conflict is found while installing Elasticsearch mappings on startup. For a detailed explanation, see <<Mapping Migrations>>.

==== `elasticSearch.migration.strategy`

Defines the behaviour to follow if an error occurs on startup when the application is installing new mappings on ElasticSearch due to conflicting mappings.

.Possible Values for migration strategy
[width="100%",cols="2",options="header"]
|===
|Value |Description

| `'none'`
|No changes on the indices or mappings will happen, the merge problem will be logged and a MappingException will be thrown.

| `'delete'`
|The conflicting mapping will be deleted (along with all indexed content of that type) and replaced with a new mapping. Deleted content can be automatically reindexed on startup by using this in combination the `elasticSearch.bulkIndexOnStartup` config option

| `'alias'`
|Applies https://www.elastic.co/docs/manage-data/data-store/aliases[Elasticsearch recommended approach for migrating conflicting mappings]. A new numbered index will be created (`<indexName>_vX`) where new mappings will installed for all the types included on the original index. An Elasticsearch alias called `<indexName>` will point to the new index. As content won't be available on the new index, content can be automatically reindexed on startup by using this in combination the `elasticSearch.bulkIndexOnStartup` config option. It is recommended to set `elasticSearch.aliasReplacesIndex` to deal with potential index/alias conflicts.

|===

[NOTE]
====
The default is `'alias'`.
====

==== `elasticSearch.migration.aliasReplacesIndex`

Deals with a special conflict case using the `'alias'` strategy. When the `'alias'` migration strategy is chosen and there's a mapping conflict on an index, defines whether to replace the index with a versioned index (`<indexName>_vX`) and an alias (`<indexName>`). This is required when applying the alias strategy on top of existing indices for the first time as indices cannot be renamed (from `<indexName>` to `<indexName>_vX`) and an alias cannot exist with the same name as an index.
	
.Possible Values for aliasReplacesIndex
[width="100%",cols="2",options="header"]
|===
|Value| Description

| `true`
| The index and it's content will be deleted and a versioned index and an alias will be created. Deleted content can be automatically reindexed on startup by using this in combination the `elasticSearch.bulkIndexOnStartup` config option

| `false`
| Falls back to the `'none'` strategy. Event will be logged and a MappingException will be thrown.

|===	

[NOTE]
====
The default is `true`.
====

==== `elasticSearch.migration.disableAliasChange`

In some cases the developer may prefer not to upgrade the alias to the new version of the index until some other tasks are performed. This allows them to disable automatically pointing the alias to a new version of the index when this is created. Aliases can be changed later on manually or programatically using `elasticSearchAdminService`

.Possible Values for disableAliasChange
[width="100%",cols="2",options="header"]
|===
| Value | Description

| `false` 
| Standard behaviour

| `true`
| Prevents the aliases to be changed to point to a new index
|===

[NOTE]
====
The default is `false`.
====

=== Dynamic Method Injection

==== `elasticSearch.searchMethodName`

Change the name of search method in domain class. By default it's `search`. 

For example

[source, groovy]
----
MyDomain.search("${params.query}")

----

[TIP]
====
In order to change the method name to `esSearch` just update the `elasticSearch.searchMethodName='esSearch'` in application.groovy
====


==== `elasticSearch.countHitsMethodName`

Change the name of countHits method in domain class. By default it's `countHits`. 

For example

[source, groovy]
----
MyDomain.countHits("${params.query}")

----

[TIP]
====
In order to change the method name to `esCountHits` just update the `elasticSearch.countHitsMethodName='esCountHits'` in application.groovy
====



==== `elasticSearch.disableDynamicMethodsInjection`

To complete disabled injection of dynamic methods set `elasticSearch.disableDynamicMethodsInjection = true` in `applicaiton.groovy` 


=== Others properties

==== `elasticSearch.datastoreImpl`

Only required when enabling the auto-index feature.
This property specifies which GORM datastore implementation should be watched for storage events.
The value should be the name of the datastore bean as it is configured in the Spring context; some possible values:

.Possible Values for datastoreImpl
[width="100%",cols="2",options="header"]
|===
| Value | Description

| mongoDatastore
| The name of the MongoDB datastore bean.

| hibernateDatastore
| The name of the Hibernate datastore bean.

|===


==== `elasticSearch.bootstrap.config.file`

If you use a modified Elasticsearch client configuration, you can use this property to specify the location of the file (as an application resource).

==== `elasticSearch.bootstrap.transportSettings.file`

When choosing transport mode this configuration will be used to set up the TransportClient settings (used by some cloud providers).

==== `elasticSearch.client.transport.sniff`

Only usable in with a transport client.
Allows to sniff the rest of the cluster, and add those into its list of machines to use.
In this case, the ip addresses used will be the ones that the other nodes were started with (the “publish” address)

==== `elasticSearch.cluster.name`

The name of the cluster for the client to join.

==== `elasticSearch.date.formats`

List of date formats used by the JSON unmarshaller to parse any date field properly.
Note : future version of the plugin may change how formats are manipulated.

==== `elasticSearch.defaultExcludedProperties`

List of domain class properties to automatically ignore (will not be indexed) if their name match one of those.
This will apply to both the default-mapped domain class, with the static `searchable` property set to "true", and when using closure mapping.
To override this setting on a specific class, it can be added to the `only` property of the `searchable` closure.

==== `elasticSearch.disableAutoIndex`

A boolean determining if the plugin should reflect any database save/update/delete automatically on the indices.
Default to `false`.

==== `elasticSearch.bulkIndexOnStartup`

Determines whether the application should launch a bulk index operation upon startup.

.Possible Values for bulkIndexOnStartup
[width="100%",cols="2",options="header"]
|===
| Value | Description

| `false`
| No indexing will happen on startup.

| `true`
| All content will be indexed on startup.

| `'deleted'`
| This value is related to the mapping migration strategy chosen. If any migration is required and any content is deleted due to it, on startup only indices and mappings lost will be indexed. More on <<Mapping Migrations>>.
|===

[NOTE]
====
Default to `true`.
====

==== `elasticSearch.index.name`
A string indicating which ElasticSearch index should be used.  If not present, will default to the package name of the domain in question.

[NOTE]
====
From Elasticsearch 5.0 on only selected settings like for instance index.codec can be set on the node level. All other settings must be set on each individual index. To set default values on every index, index templates should be used instead. So, unset this value if you are using Elasticsearch v5.0 or above. As a workaround elasticSearch.index.prefix setting can be used.
====

==== `elasticSearch.index.prefix`
The setting provides possibility to add prefix to all index and alias names of application. Can be useful in setup of many applications with one ES instance. Mostly, that is a replacement of elasticSearch.index.name for ES 5.0 +

==== `elasticSearch.index.store.type`

Determine how the indices will be stored.
More details on the possible values on the https://www.elastic.co/guide/en/elasticsearch/reference/7.17/index-modules-store.html[ElasticSearch Documentation].

.Possible value for index store type
[width="100%",cols="2",options="header"]
|===
| Value | Description

| memory 
| Stores the index in memory. Useful for testing. *Please note* that it's not support in ES 2.0 and later versions.

| mmapfs
| Stores the shard index on the file system (maps to Lucene MMapDirectory) using mmap.

| niofs
| Stores the shard index on the file system (maps to Lucene NIOFSDirectory) and allows for multiple threads to read from the same file concurrently.

| simplefs
| Stores using a plain forward implementation of file system storage (maps to Lucene SimpleFsDirectory) using random access file.

|===

==== `elasticSearch.index.settings.numberOfReplicas`

Sets the number of replicas created for each shard of the index. If not present, will default to zero.

==== `elasticSearch.maxBulkRequest`

Max number of requests to process at once.
Reduce this value if you have memory issue when indexing a big amount of data at once.
If this setting is not specified, 500 will be use by default.

==== `elasticSearch.path.data`

The location of the data files of each index / shard allocated on the node.

==== `elasticSearch.path.plugins`

The location of plugin files such as native scripts. Each plugin will be contained in a subdirectory.

==== `elasticSearch.searchableProperty.name`

The name of the ElasticSearch mapping configuration property that annotates domain classes. The default is 'searchable'.

==== `elasticSearch.includeTransients`

Whether to index and search all non excluded transient properties. All explicitly included transients in `only` will be indexed regardless.

[NOTE]
====
Default is `false`.
====
